In [32]:
#Mansoor Ahmed
#Roll no: P15-6069
#Machine Learning
#Assignment #3

import numpy as np

# X = (Total hrs of Sleeping, Total hrs of Studying), y = score on test
X = np.array(([3, 8], [2, 6], [2, 5]), dtype=float)
y = np.array(([93], [87], [90]), dtype=float)

# scaling the units
X = X/np.amax(X, axis=0) 
y = y/100 # maximum text score is 100

class Neural_Network(object):
    
  def __init__(self):
    
    self.input_size = 2
    self.output_size = 1
    self.hidden_size = 3

    #weights
    self.weight1 = np.random.randn(self.input_size, self.hidden_size) 
    self.weight2 = np.random.randn(self.hidden_size, self.output_size) 

  def forward_pass(self, X):
    
    self.z = np.dot(X, self.weight1)
    self.z2 = self.sig_fun(self.z) 
    self.z3 = np.dot(self.z2, self.weight2)
    output = self.sig_fun(self.z3)
    return output 

  def sig_fun(self, z):
    
    return 1/(1+np.exp(-z))

  def sig_deriv(self, z):
    
    return z * (1 - z)

  def backward_pass(self, X, y, output):
    
    self.output_error = y - output # error in output
    self.output_delta = self.output_error*self.sig_deriv(output) # applying derivative of sig_fun to error

    self.z2_error = self.output_delta.dot(self.weight2.T) 
    self.z2_delta = self.z2_error*self.sig_deriv(self.z2) 

    self.weight1 += X.T.dot(self.z2_delta)
    self.weight2 += self.z2.T.dot(self.output_delta) 

  def train (self, X, y):
    
    output = self.forward_pass(X)
    self.backward_pass(X, y, output)

NeuralNet = Neural_Network()
for epochs in range(200): 
  print("Input: \n" + str(X))
  print("Real Output: \n" + str(y)) 
  print("Output Prediction: \n" + str(NeuralNet.forward_pass(X)) )
  print("Cost: \n" + str(np.mean(np.square(y - NeuralNet.forward_pass(X))))) # mean squared loss
  print("\n")
  NeuralNet.train(X, y)

Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.43468101]
 [ 0.42742647]
 [ 0.43529339]]
Cost: 
0.219054820118


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.53745687]
 [ 0.52278432]
 [ 0.52951508]]
Cost: 
0.137302636977


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.61682008]
 [ 0.59754321]
 [ 0.60306397]]
Cost: 
0.0868284562114


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.67397524]
 [ 0.65220835]
 [ 0.65667428]]
Cost: 
0.0573964290263


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.9

Output Prediction: 
[[ 0.90703039]
 [ 0.8881544 ]
 [ 0.88730263]]
Cost: 
0.000339469448754


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.90721937]
 [ 0.88835985]
 [ 0.88750488]]
Cost: 
0.000337389727011


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.90740065]
 [ 0.88855692]
 [ 0.88769891]]
Cost: 
0.000335468907602


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.90757458]
 [ 0.88874599]
 [ 0.8878851 ]]
Cost: 
0.000333694153646


Input: 
[[ 1.          1.        ]
 [ 0.66666667  0.75      ]
 [ 0.66666667  0.625     ]]
Real Output: 
[[ 0.93]
 [ 0.87]
 [ 0.9 ]]
Output Prediction: 
[[ 0.90774151]
 [ 0.88892744]
 [ 0.8880638 ]]
Cost: 
0.000332053731845


Input: 